/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author suraj ravihara
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel_BICT = new javax.swing.JLabel();
        jButton_Network = new javax.swing.JButton();
        jButton_Software = new javax.swing.JButton();
        jButton_Multimedia = new javax.swing.JButton();
        jLabel_01 = new javax.swing.JLabel();
        jLabel_02 = new javax.swing.JLabel();
        jLabel_03 = new javax.swing.JLabel();
        jButton_Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel_BICT.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel_BICT.setForeground(new java.awt.Color(51, 51, 255));
        jLabel_BICT.setText("BICT courses \n(Bachelor of Information and Communication Technology.)");

        jButton_Network.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton_Network.setText("Network Technology");
        jButton_Network.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NetworkActionPerformed(evt);
            }
        });

        jButton_Software.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton_Software.setText("Software Technology");
        jButton_Software.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SoftwareActionPerformed(evt);
            }
        });

        jButton_Multimedia.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton_Multimedia.setText("Multimedia & Grapic Design");
        jButton_Multimedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MultimediaActionPerformed(evt);
            }
        });

        jLabel_01.setText("01");

        jLabel_02.setText("02");

        jLabel_03.setText("03");

        jButton_Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Back.setForeground(new java.awt.Color(0, 0, 255));
        jButton_Back.setText("Log out");
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel_BICT, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jButton_Back))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_01)
                            .addComponent(jLabel_02)
                            .addComponent(jLabel_03))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Multimedia, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Software, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Network, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_BICT, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Network)
                    .addComponent(jLabel_01))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Software)
                    .addComponent(jLabel_02))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Multimedia)
                    .addComponent(jLabel_03))
                .addGap(45, 45, 45)
                .addComponent(jButton_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
         new loginform ().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jButton_NetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NetworkActionPerformed
        new Network ().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton_NetworkActionPerformed

    private void jButton_SoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SoftwareActionPerformed
           new Software ().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton_SoftwareActionPerformed

    private void jButton_MultimediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MultimediaActionPerformed
         new Multimedia ().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton_MultimediaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Multimedia;
    private javax.swing.JButton jButton_Network;
    private javax.swing.JButton jButton_Software;
    private javax.swing.JLabel jLabel_01;
    private javax.swing.JLabel jLabel_02;
    private javax.swing.JLabel jLabel_03;
    private javax.swing.JLabel jLabel_BICT;
    // End of variables declaration//GEN-END:variables
}
